// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/f-rambo/ship/internal/biz"
	"github.com/f-rambo/ship/internal/conf"
	"github.com/f-rambo/ship/internal/data"
	"github.com/f-rambo/ship/internal/interfaces"
	"github.com/f-rambo/ship/internal/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(logger)
	if err != nil {
		return nil, nil, err
	}
	systemRepo := data.NewSystemRepo(dataData, logger)
	systemUsecase := biz.NewSystemUseCase(systemRepo, logger)
	systemInterface := interfaces.NewSystemInterface(systemUsecase, logger, confServer)
	cloudRepo := data.NewCloudRepo(dataData, logger)
	cloudUsecase := biz.NewCloudUseCase(confServer, cloudRepo, logger)
	cloudInterface := interfaces.NewCloudInterface(cloudUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, systemInterface, cloudInterface, logger)
	httpServer := server.NewHTTPServer(confServer, systemInterface, cloudInterface, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
