FROM golang:1.22 AS builder

COPY . /src
WORKDIR /src

ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn
ENV GOPRIVATE=github.com/f-rambo/
ENV CGO_ENABLED=1

RUN make build && mkdir -p /app && cp -r bin /app/ && cp -r configs /app/

FROM debian:stable-slim

COPY --from=builder /app /app

RUN tar -czvf /app.tar.gz /app
