// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/f-rambo/cloud-copilot/sidecar/internal/biz"
	"github.com/f-rambo/cloud-copilot/sidecar/internal/conf"
	"github.com/f-rambo/cloud-copilot/sidecar/internal/interfaces"
	"github.com/f-rambo/cloud-copilot/sidecar/internal/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, logger log.Logger) (*kratos.App, func(), error) {
	clusterUsecase := biz.NewClusterUseCase(logger)
	clusterInterface := interfaces.NewClusterInterface(clusterUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, clusterInterface, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
